Homework22/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('users/', include("users.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Homework22/hw_project/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView,PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                     redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('reset-password/',ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

Homework22/hw_project/users/models.py
from django.db import models

# Create your models here.

Homework22/hw_project/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput



class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=150, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=150, widget=TextInput(attrs={"class": "form-control"}))
    email =EmailField(max_length=150, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=20, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=20, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=20, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))


    class Meta:
        fields = ['username', 'password']

Homework22/hw_project/users/views.py
from django.shortcuts import render
from django.views import View
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView

from .forms import RegisterForm
# Create your views here.
class RegisterView(View):
   form_class = RegisterForm
   template_name ="users/signup.html"

   def dispatch(self, request, *args, **kwargs):
       if request.user.is_authenticated:
           return redirect(to="quotes:root")
       return super(RegisterView, self).dispatch(request, *args, **kwargs)

   def get(self, request):
       return render(request, self.template_name, {"form": self.form_class})

   def post(self, request):
       form = self.form_class(request.POST)
       # print(form)
       if form.is_valid():
           form.save()
           username = form.cleaned_data['username']
           messages.success(request, f'Вітаю {username}. Ваш акаунт успішно створено')
           print('Redirecting to users:login')

           return redirect(to="users:login")
       return render(request, self.template_name, {"form": form})
       
       
       
class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

Homework22/hw_project/users/templates/users/logout.html
{% extends 'quotes/base.html' %}

{% block content %}
  <a href="/" class="back-button">← TO MAIN</a>
  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <h1 class="text-center-1">You are out!!!</h1>
          </div>
          <div class="card-body">
            <p class="text-center-1">Thank you for using our site. We will be glad to see you again!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Homework22/hw_project/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}


{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}


{% block content %}
<style>
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }

    label {
        width: 100%;
    }

    input {
        width: 100%;
    }
</style>
<div class="form-signin rounded-3 bg-light">
    <h2>Password reset</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-center">
         <button type="submit" class="btn btn-primary">Request password reset</button>
        </div>

    </form>
</div>

{% endblock %}

Homework22/hw_project/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

Homework22/hw_project/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% block content %}
<style>
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }

    label {
        width: 100%;
    }
    
    input {
        width: 100%;
    }
</style>
<div class="form-signin rounded-3 bg-light">
<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Save new password</button>
    </div>
</form>
</div>

{% endblock %}

Homework22/hw_project/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

Homework22/hw_project/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

Homework22/hw_project/users/templates/users/signin.html
{% extends 'quotes/base.html' %}


{% block content %}

<a href="/" class="back-button">← TO MAIN</a>
<h1>Sidn IN</h1>
{% if messages %}
    {% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
    {% endfor %}
{% endif%}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{form.non_field_errors}}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <lable class="form-label">Username</lable>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <lable class="form-label">PASSWORD</lable>
            {{form.password}}
        </div>
        <span>{{form.errors.password}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sign IN</button>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>
{% endblock %}

Homework22/hw_project/users/templates/users/signup.html
{% extends 'quotes/base.html' %}


{% block content %}
<h1>SidnUp</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <lable class="form-label">Username</lable>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <lable class="form-label">First Name</lable>
            {{form.first_name}}
        </div>
        <span>{{form.errors.first_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <lable class="form-label">Last Name</lable>
            {{form.last_name}}
        </div>
        <span>{{form.errors.last_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <lable class="form-label">Email</lable>
            {{form.email}}
        </div>
        <span>{{form.errors.email}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <lable class="form-label">Password</lable>
            {{form.password1}}
        </div>
        <span>{{form.errors.password1}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <lable class="form-label">Confirm Password</lable>
            {{form.password2}}
        </div>
        <span>{{form.errors.password2}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sign UP</button>
</form>
{% endblock %}