Homework22/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('users/', include("users.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Homework22/hw_project/quotes/urls.py
from django.urls import path
from . import views


app_name = "quotes"

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('add_author/', views.add_author, name='add_author'),
    path('author_detail/<int:author_id>/', views.author_detail, name='author_detail'),
    path('tag_detail/<int:tag_id>/', views.tag_detail, name='tag_detail'),
    path('quote_detail/<int:quote_id>', views.quote_detail, name='quote_detail'),
    path('delete_quote/<int:quote_id>/', views.delete_quote, name='delete_quote'),
    path('edit_quote/<int:quote_id>/', views.edit_quote, name='edit_quote'),
    path('upload/', views.upload, name='upload'),
    path("pictures/", views.pictures, name='pictures'),
    path("edit_picture/<int:pic_id>", views.edit_picture, name='edit_picture'),
    path("remove_picture/<int:pic_id>", views.remove_picture, name='remove_picture'),
]

Homework22/hw_project/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView,PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                     redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('reset-password/',ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

Homework22/hw_project/quotes/models.py
from django.db import models
from uuid import uuid4
import os
from django.core.exceptions import ValidationError

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False,unique=True)

    def __str__(self):
        return self.name

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)



def update_filename(instance, filename):
    upload_to = 'uploads'
    ext = filename.split('.')[-1]
    filename = f"{uuid4().hex}.{ext}"
    return os.path.join(upload_to, filename)


def validate_file_size(value):
    file_size = value.size
    if file_size > 1000000:
        raise ValidationError("The maximum file size is greater than 1 MB")
    return value


class Picture(models.Model):
    description = models.CharField(max_length=200)
    path = models.ImageField(upload_to=update_filename, validators=[validate_file_size])

Homework22/hw_project/quotes/forms.py
from django.forms import ModelForm, ImageField, CharField, FileInput,TextInput
from .models import Tag, Quote, Author, Picture
from django import forms


class TagForm(ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    class Meta:
        model = Tag
        fields = ['name', 'tags']


class QuoteForm(ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']




class PictureForm(ModelForm):
    description = CharField(max_length=200, widget=TextInput(attrs={"class":"form-control"}))
    path = ImageField(widget=FileInput(attrs={"class":"form-control"}))

    class Meta:
        model = Picture
        fields = ['description', 'path']

Homework22/hw_project/quotes/views.py
import os

from django.core.paginator import Paginator
from .models import Author
from django.shortcuts import render, redirect, get_object_or_404
from .models import Quote, Tag, Picture
from .forms import QuoteForm, TagForm, AuthorForm, PictureForm
from django.db.models import Count
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.conf import settings



def main(request, page=1):
    quotes = Quote.objects.all()
    tags = Tag.objects.annotate(quote_count=Count('quote')).order_by('-quote_count')
    top_tags = tags[:10]
    per_page = 15
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)

    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page, 'tags': top_tags})


def add_quote(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            try:

                selected_tag = form.cleaned_data['tags'][0]
                new_quote = form.save()
                new_quote.tags.add(selected_tag)
                return redirect(to="quotes:root")
            except ValueError as err:
                return render(request, 'quotes/add_quote.html', {"tags": tags, 'form': QuoteForm(), 'error': err})
    return render(request, 'quotes/add_quote.html', {"tags": tags, 'form': QuoteForm()})


@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            try:
                tag = form.save()
                return redirect('quotes:root')
            except IntegrityError as err:
                return render(request, 'quotes/add_tag.html', {'form': form, 'error': f'IntegrityError: {err}'})
            except ValueError as err:
                return render(request, 'quotes/add_tag.html', {'form': TagForm(), 'error': err})
        else:
            return render(request, 'quotes/add_tag.html', {'form': form, 'error': form.errors})
    else:
        return render(request, 'quotes/add_tag.html', {'form': TagForm()})



@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('quotes:root')
            except IntegrityError as err:
                return render(request, 'quotes/add_author.html', {'form': form, 'error': f'IntegrityError: {err}'})
            except ValueError as err:
                return render(request, 'quotes/add_author.html', {'form': AuthorForm(), 'error': err})
        else:
            print(f'Form is not valid: {form.errors}')
            return render(request, 'quotes/add_author.html', {'form': form, 'error': form.errors})
    else:
        return render(request, 'quotes/add_author.html', {'form': AuthorForm()})

def author_detail(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    quotes_by_author = author.quote_set.all()

    context = {'author': author, 'quotes_by_author': quotes_by_author}
    return render(request, 'quotes/author_detail.html', context)

def tag_detail(request, tag_id):
    tag = get_object_or_404(Tag, id=tag_id)
    quotes = Quote.objects.filter(tags=tag)
    context = {'tag': tag, 'quotes_10':quotes}
    return render(request, 'quotes/tag_detail.html', context)

@login_required
def quote_detail(request, quote_id):
    quote = get_object_or_404(Quote, id=quote_id)
    return render(request, 'quotes/quote_detail.html', {'quote': quote})


@login_required
def delete_quote(request, quote_id):
    quote = Quote.objects.get(pk= quote_id)
    quote.delete()
    messages.success(request, 'Quote successfully deleted!')
    return render(request, 'quotes/quote_edit_deleted.html')

@login_required
def edit_quote(request, quote_id):
    quote = get_object_or_404(Quote, id=quote_id)

    if request.method == 'POST':
        form = QuoteForm(request.POST, instance=quote)
        if form.is_valid():
            form.save()
            messages.success(request, 'Quote successfully edited!')
            return render(request, 'quotes/quote_edit_deleted.html')
    else:
        form = QuoteForm(instance=quote)

    return render(request, 'quotes/quote_edit.html', {'form': form, 'quote': quote})


@login_required
def upload(request):
    form = PictureForm(instance=Picture())
    if request.method == 'POST':
        form = PictureForm(request.POST, request.FILES, instance=Picture())
        if form.is_valid():
            form.save()
            return redirect('quotes:root')
    return render(request, 'quotes/upload.html', context={"form": form})



@login_required
def pictures(request):
    pictures = Picture.objects.all()
    return render(request, 'quotes/picture.html', context={"pictures": pictures})


@login_required
def edit_picture(request, pic_id):
    if request.method == 'POST':
        description = request.POST.get('description')
        Picture.objects.filter(pk=pic_id).update(description=description)
        return redirect('quotes:root')
    picture = Picture.objects.filter(pk=pic_id).first()
    return render(request, "quotes/edit_picture.html",
           context={"pic": picture, "media": settings.MEDIA_URL})


@login_required
def remove_picture(request, pic_id):
    picture = Picture.objects.filter(pk=pic_id)
    try:
        os.unlink(os.path.join(settings.MEDIA_ROOT, str(picture.first().path)))
    except OSError as err:
        print(err)
    picture.delete()
    return redirect('quotes:root')

Homework22/hw_project/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}

<a href="/" class="back-button">← TO MAIN</a>
<div class="container_add">
    <h2 class="page-title">Add a New Author</h2>

    {% if error %}
    <div class="alert alert-danger" role="alert">
        <strong>Error:</strong> {{ error }}
    </div>
    {% endif %}

    <form method="POST" class="author-form">
        {% csrf_token %}

        <div class="form-group">
            <label class="form-label">Full Name:</label>
            {{ form.fullname }}
        </div>

        <div class="form-group">
            <label class="form-label">Born Date:</label>
            {{ form.born_date }}
        </div>

        <div class="form-group">
            <label class="form-label">Born Location:</label>
            {{ form.born_location }}
        </div>

        <div class="form-group">
            <label class="form-label">Description:</label>
            {{ form.description }}
        </div>

        <div class="grid">
            <button type="submit" class="btn submit-btn">Submit</button>
            <button type="reset" class="btn reset-btn">Reset</button>
        </div>
    </form>
</div>

{% endblock %}

Homework22/hw_project/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block content %}

<a href="/" class="back-button">← TO MAIN</a>
<div class="container_add">
    <h2 class="page-title">Add a New Quote</h2>

    {% if error %}
    <div class="alert alert-danger" role="alert">
        <strong>Error:</strong> {{ error }}
    </div>
    {% endif %}

    <form method="POST" class="quote-form">
        {% csrf_token %}

        <div class="form-group">
            <label class="form-label">Quote:</label>
            {{ form.quote }}
        </div>

        <div class="form-group">
            <label class="form-label" for="id_tags">Tags:</label>
            <select name="tags" id="id_tags" class="form-select" required>
                {% for tag in form.tags.field.queryset %}
                <option value="{{ tag.id }}">{{ tag.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label class="form-label" for="id_author">Author:</label>
            <select name="author" id="id_author" class="form-select" required>
                <option value="" disabled selected>Select an author</option>
                {% for author in form.author.field.queryset %}
                <option value="{{ author.id }}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="grid">
            <button type="submit" class="btn submit-btn">Submit</button>
            <button type="reset" class="btn reset-btn">Reset</button>
        </div>
    </form>
</div>

{% endblock %}

Homework22/hw_project/quotes/templates/quotes/add_tag.html
{% extends 'quotes/base.html' %}

{% block content %}
<a href="/" class="back-button">← TO MAIN</a>
{% if error %}
<div class="alert alert-danger" role="alert">
    <strong>Error:</strong> {{ error }}
</div>
    {% endif %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <h1>Enter the tag name:</h1>
        <label class="form-label_add_tag">
            {{ form.name }}
        </label>
    </div>
    <div class="grid">
            <button type="submit" class="btn submit-btn">Submit</button>
            <button type="reset" class="btn reset-btn">Reset</button>
    </div>
</form>

{% endblock %}

Homework22/hw_project/quotes/templates/quotes/author_biography.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h1>{{ author.fullname }}</h1>

    <p>Born: {{ author.born_date }} in {{ author.born_location }}</p>
    <p>Description: {{ author.description }}</p>

    <h2>Quotes by {{ author.fullname }}</h2>
    {% for quote in quotes_by_author %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                    <a class="tag" href="/tag/{{ keyword }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

Homework22/hw_project/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="author_content">
    <a href="/" class="back-button">← TO MAIN</a>
    <h1>{{ author.fullname }}</h1>
    <p class="author">Born: {{ author.born_date }} in {{ author.born_location }}</p>
    <p class="author">Description: {{ author.description }}</p>
</div>
<h2>Quotes by {{ author.fullname }}</h2>
<div class="author_quotes">
    {% for quote in quotes_by_author %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{ quote.quote }}</span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag"  href="{% url 'quotes:tag_detail' tag.id %}">{{ tag.name }}</a>
            {% endfor %}
        </div>
        {% if user.is_authenticated %}
        <a class="read_btn" href="{% url 'quotes:quote_detail' quote.id %}">READ</a>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock %}

Homework22/hw_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=0.85, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <title>Homework</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
</head>
<body>
{% load extract %}
<div class="container">
    <div class="row header-box">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
            {% if request.path|is_add_quote_page and user.is_authenticated %}
           <ul class="bt_add">
                <li><a class="add_btn" href="{% url 'quotes:add_quote' %}">&#8853; ADD QUOTE</a></li>
                <li><a class="add_btn" href="{% url 'quotes:add_tag' %}">&#8853; ADD TAG</a></li>
                <li><a class="add_btn" href="{% url 'quotes:add_author' %}">&#8853; ADD AUTHOR</a></li>
                <li><a class="add_btn" href="{% url 'quotes:upload' %}">&#8853; Upload phote</a></li>
                <li><a class="add_btn" href="{% url 'quotes:pictures' %}">&#8853; Pictures</a></li>
           </ul>
            {% endif %}
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                {% else %}
                <a href="{% url 'users:register' %}" class="btn btn-primary">SignUp</a>
                <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                {% endif %}
            </p>
        </div>
    </div>
    {% block content %} {% endblock %}
</div>
<footer class="footer_down">
    <div class="container_footer">
        <p class="text-muted">
            Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
        </p>
        <p class="copyright">
            Made with <span class="zyte">&hearts;</span> by <a class="zyte" href="https://www.zyte.com">Zyte</a>
        </p>
    </div>
</footer>
</body>
</html>

Homework22/hw_project/quotes/templates/quotes/edit_picture.html
{% extends 'quotes/base.html' %}

{% block content %}

<a href="/" class="back-button">← TO MAIN</a>
<h1>Upload file</h1>
<form action="" method="post">
    {% csrf_token %}
    <img src="{{pic.path.url}}" width="350" height="350" alt="pic">
    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" value="{{pic.description}}" name="description">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

Homework22/hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.id|author}}</small>
            <a class="about" href="{% url 'quotes:author_detail' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:tag_detail' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
            <a class="read_btn" href="{% url 'quotes:quote_detail' quote.id %}">READ</a>
            {% endif %}
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next
                        <span aria-hidden="true">→</span></a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="col-md-4 tags-box">
        <h2>Top Ten tags</h2>
        {% for tag in tags %}
        <a class="tag_10" href="{% url 'quotes:tag_detail' tag.id %}"
           style="font-size: {{ forloop.counter|calculate_font_size }}px;">{{ tag.name }}</a>
        {% endfor %}
       <img src="./static/picture/picture1.png" alt="Alt">
    </div>
</div>
{% endblock %}

Homework22/hw_project/quotes/templates/quotes/picture.html
{% extends 'quotes/base.html' %}

{% block content %}

<a href="/" class="back-button">← TO MAIN</a>
<h1>Your picture</h1>
<div class="row">
    {% for pic in pictures %}
    <div class="card" style="width: 18rem;">
        <img src="{{pic.path.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">{{pic.description}}</p>
            <a href="{% url 'quotes:edit_picture' pic.id %}" class="btn btn-primary">Edit</a>
            <a href="{% url 'quotes:remove_picture' pic.id %}" class="btn btn-primary">Delete</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

Homework22/hw_project/quotes/templates/quotes/quote_detail.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<a href="/" class="back-button">← TO MAIN</a>
<h4> Quote author: {{quote.author}}</h4>
<div class="quote_selected" itemscope="" itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">{{quote.quote}}</span>
    <span>by <small class="author" itemprop="author">{{quote.author.id|author}}</small>
            <a class="about" href="{% url 'quotes:author_detail' quote.author.id %}">(about)</a>
        </span>
    <div class="tags">
        Tags:
        {% for tag in quote.tags.all %}
        <a class="tag" href="{% url 'quotes:tag_detail' tag.id %}">{{tag.name}}</a>
        {% endfor %}
    </div>
</div>
<div class="buttons_e_d">
    <a class="edit_btn" href="{% url 'quotes:edit_quote' quote.id %}">Edit</a>
    <a class="delete_btn" href="{% url 'quotes:delete_quote' quote.id %}">Delete</a>
</div>
{% endblock %}

Homework22/hw_project/quotes/templates/quotes/quote_edit.html
{% extends 'quotes/base.html' %}

{% block content %}
<a href="/" class="back-button">← TO MAIN</a>
<div class="container_add">
    <h2 class="page-title">Edit a Quote</h2>
    {% if error %}
    <div class="alert alert-danger" role="alert">
        <strong>Error:</strong> {{ error }}
    </div>
    {% endif %}
    <form method="POST" class="quote-form">
        {% csrf_token %}
        <div class="form-group">
            <label class="form-label">Quote:</label>
            {{ form.quote }}
        </div>
        <div class="form-group">
            <label class="form-label" for="id_tags">Tags:</label>
            <select name="tags" id="id_tags" class="form-select" required>
                {% for tag in form.tags.field.queryset %}
                <option value="{{ tag.id }}">{{ tag.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label class="form-label" for="id_author">Author:</label>
            <select name="author" id="id_author" class="form-select" required>
                <option value="" disabled selected>Select an author</option>
                {% for author in form.author.field.queryset %}
                <option value="{{ author.id }}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="grid">
            <button type="submit" class="btn submit-btn">Save</button>
            <a href="#" class="btn reset-btn">Reset</a>
        </div>
    </form>
</div>
{% endblock %}

Homework22/hw_project/quotes/templates/quotes/quote_edit_deleted.html
{% extends 'quotes/base.html' %}


{% block content %}

<a href="/" class="back-button">← TO MAIN</a>
<div class="deleted">
 {% if messages %}
    {% for message in messages %}
<div {% if message.tags %} class="text-center" {% endif %} role="alert">
    {{message}}
</div>
    {% endfor %}
{% endif%}
</div>

{% endblock %}

Homework22/hw_project/quotes/templates/quotes/tag_detail.html
{% extends 'quotes/base.html' %}

{% block content %}


<a href="/" class="back-button">← TO MAIN</a>
<h1> Tag: {{ tag.name }}</h1>
{% for quote in quotes_10 %}
<div class="quote_selected" itemscope="" itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">{{quote.quote}}</span>
    <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a class="about" href="{% url 'quotes:author_detail' quote.author.id %}">(about)</a>
    </span>
    <div class="tags">
        Tags:
        {% for tag in quote.tags.all %}
        <a class="tag" href="{% url 'quotes:tag_detail' tag.id %}">{{tag.name}}</a>
        {% endfor %}
    </div>
    {% if user.is_authenticated %}
    <a class="read_btn" href="{% url 'quotes:quote_detail' quote.id %}">READ</a>
    {% endif %}
</div>
{% endfor %}

{% endblock %}

Homework22/hw_project/quotes/templates/quotes/upload.html
{% extends 'quotes/base.html' %}

{% block content %}

<a href="/" class="back-button">← TO MAIN</a>
<div class="container mt-3">
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Description</label>
            {{form.description}}
            <span>{{form.errors.description}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Picture</label>
            {{form.path}}
            <span>{{form.errors.path}}</span>
        </div>
        <div class="grid">
            <button type="submit" class="btn submit-btn">Submit</button>
            <button type="reset" class="btn reset-btn">Reset</button>
        </div>
    </form>
</div>
{% endblock %}